# Generated by Django 4.0.6 on 2023-03-13 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('umoji', '0005_alter_managementreport_total_attendace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('wsf_centre_name', models.CharField(max_length=40)),
                ('total_sunday_attendance', models.IntegerField()),
                ('avg_sunday_attendance', models.IntegerField()),
                ('avg_adults', models.IntegerField()),
                ('avg_children', models.IntegerField()),
                ('avg_chop', models.IntegerField()),
                ('avg_wsf', models.IntegerField()),
                ('no_of_wsf', models.IntegerField()),
                ('bfc', models.IntegerField()),
                ('highest_sunday_attendance', models.IntegerField()),
                ('first_timers', models.IntegerField()),
                ('new_converts', models.IntegerField()),
                ('Total_income', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
