# Generated by Django 4.0.6 on 2023-03-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umoji', '0006_church'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='wsf_centre_name',
        ),
    ]
