# Generated by Django 4.0.6 on 2023-03-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoji', '0007_remove_church_wsf_centre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='avg_adults',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='avg_children',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='avg_chop',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='avg_sunday_attendance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='avg_wsf',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='bfc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='first_timers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='new_converts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='total_sunday_attendance',
            field=models.IntegerField(null=True),
        ),
    ]
