# Generated by Django 4.0.6 on 2023-03-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoji', '0010_announcement_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kap',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='managementreport',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='media',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wsf',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wsfleaders',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
