# Generated by Django 4.0.5 on 2023-03-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umoji', '0012_church_avg_midweek_attendance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wsf',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
