# Generated by Django 4.0.5 on 2023-03-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umoji', '0013_alter_wsf_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wsf',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wsfleaders',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
