# Generated by Django 4.0.5 on 2023-03-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umoji', '0014_alter_wsf_options_alter_wsfleaders_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'permissions': [('pastor', 'Can acess pastor')]},
        ),
    ]
