# Generated by Django 4.0.5 on 2023-03-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umoji', '0015_alter_church_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementreport',
            options={'permissions': [('elder', 'for cmc')]},
        ),
    ]
