# Generated by Django 4.0.5 on 2023-03-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umoji', '0017_alter_church_options_alter_managementreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicereport',
            options={'permissions': [('ushers', 'for ushers'), ('ushers alone', 'only ushers')]},
        ),
    ]
