# Generated by Django 4.0.5 on 2023-03-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umoji', '0018_alter_servicereport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wsfleaders',
            options={'permissions': [('special_status', 'Can read all books'), ('special', 'only wsf')]},
        ),
    ]
